M48
; DRILL file {KiCad 9.0.6} date 2025-11-24T11:02:40+0800
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-11-24T11:02:40+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0228
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0260
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1260
%
G90
G05
T2
X5.1472Y-4.502
T3
X5.7087Y-5.7087
T1
G00X5.1472Y-4.215
M15
G01X5.1472Y-4.1984
M16
G05
M30
